# Changes here will be overwritten by Copier
_commit: 9642da9
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: 1kbgz
project_description: My Pocket Knife
project_name: pkn
python_version_primary: '3.11'
team: 1kbgz
