# Changes here will be overwritten by Copier
_commit: 54b9adc
_src_path: git@github.com:python-project-templates/base.git
add_extension: python
email: 3105306+timkpaine@users.noreply.github.com
github: timkpaine
project_description: My Pocket Knife
project_name: pkn
python_version_primary: '3.11'
team: timkpaine
